// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: proto/paperStorageServer.proto

package paperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Paper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int32                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paper) Reset() {
	*x = Paper{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paper) ProtoMessage() {}

func (x *Paper) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paper.ProtoReflect.Descriptor instead.
func (*Paper) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{0}
}

func (x *Paper) GetPaperId() int32 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *Paper) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Paper) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Paper) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Paper) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AddPaperArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paper         *Paper                 `protobuf:"bytes,1,opt,name=paper,proto3" json:"paper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaperArgs) Reset() {
	*x = AddPaperArgs{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaperArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaperArgs) ProtoMessage() {}

func (x *AddPaperArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaperArgs.ProtoReflect.Descriptor instead.
func (*AddPaperArgs) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{1}
}

func (x *AddPaperArgs) GetPaper() *Paper {
	if x != nil {
		return x.Paper
	}
	return nil
}

type AddPaperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaperResponse) Reset() {
	*x = AddPaperResponse{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaperResponse) ProtoMessage() {}

func (x *AddPaperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaperResponse.ProtoReflect.Descriptor instead.
func (*AddPaperResponse) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{2}
}

func (x *AddPaperResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListPapersArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPapersArgs) Reset() {
	*x = ListPapersArgs{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPapersArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPapersArgs) ProtoMessage() {}

func (x *ListPapersArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPapersArgs.ProtoReflect.Descriptor instead.
func (*ListPapersArgs) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{3}
}

type ListPapersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Papers        []*Paper               `protobuf:"bytes,1,rep,name=papers,proto3" json:"papers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPapersResponse) Reset() {
	*x = ListPapersResponse{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPapersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPapersResponse) ProtoMessage() {}

func (x *ListPapersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPapersResponse.ProtoReflect.Descriptor instead.
func (*ListPapersResponse) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{4}
}

func (x *ListPapersResponse) GetPapers() []*Paper {
	if x != nil {
		return x.Papers
	}
	return nil
}

type GetPaperDetailsArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int32                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaperDetailsArgs) Reset() {
	*x = GetPaperDetailsArgs{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaperDetailsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperDetailsArgs) ProtoMessage() {}

func (x *GetPaperDetailsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperDetailsArgs.ProtoReflect.Descriptor instead.
func (*GetPaperDetailsArgs) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaperDetailsArgs) GetPaperId() int32 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

type GetPaperDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paper         *Paper                 `protobuf:"bytes,1,opt,name=paper,proto3" json:"paper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaperDetailsResponse) Reset() {
	*x = GetPaperDetailsResponse{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaperDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperDetailsResponse) ProtoMessage() {}

func (x *GetPaperDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetPaperDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaperDetailsResponse) GetPaper() *Paper {
	if x != nil {
		return x.Paper
	}
	return nil
}

type FetchPaperContentArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int32                  `protobuf:"varint,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPaperContentArgs) Reset() {
	*x = FetchPaperContentArgs{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPaperContentArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPaperContentArgs) ProtoMessage() {}

func (x *FetchPaperContentArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPaperContentArgs.ProtoReflect.Descriptor instead.
func (*FetchPaperContentArgs) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{7}
}

func (x *FetchPaperContentArgs) GetPaperId() int32 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

type FetchPaperContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPaperContentResponse) Reset() {
	*x = FetchPaperContentResponse{}
	mi := &file_proto_paperStorageServer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPaperContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPaperContentResponse) ProtoMessage() {}

func (x *FetchPaperContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperStorageServer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPaperContentResponse.ProtoReflect.Descriptor instead.
func (*FetchPaperContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_paperStorageServer_proto_rawDescGZIP(), []int{8}
}

func (x *FetchPaperContentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_proto_paperStorageServer_proto protoreflect.FileDescriptor

var file_proto_paperStorageServer_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x05, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x50, 0x61, 0x70, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x05, 0x70, 0x61, 0x70, 0x65, 0x72, 0x22, 0x2a,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x73, 0x41, 0x72, 0x67, 0x73, 0x22, 0x49, 0x0a, 0x12,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x61, 0x70, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52,
	0x06, 0x70, 0x61, 0x70, 0x65, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x70, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x70, 0x61, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x05, 0x70, 0x61, 0x70, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x15, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x19, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x32, 0xab, 0x03, 0x0a, 0x13, 0x50, 0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x61, 0x70, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x26, 0x2e, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x73,
	0x12, 0x24, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x70, 0x65,
	0x72, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x28, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x29, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x70, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x2d,
	0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a,
	0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x2b, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x2f, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x70, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x1e, 0x5a, 0x1c, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_paperStorageServer_proto_rawDescOnce sync.Once
	file_proto_paperStorageServer_proto_rawDescData = file_proto_paperStorageServer_proto_rawDesc
)

func file_proto_paperStorageServer_proto_rawDescGZIP() []byte {
	file_proto_paperStorageServer_proto_rawDescOnce.Do(func() {
		file_proto_paperStorageServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_paperStorageServer_proto_rawDescData)
	})
	return file_proto_paperStorageServer_proto_rawDescData
}

var file_proto_paperStorageServer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_paperStorageServer_proto_goTypes = []any{
	(*Paper)(nil),                     // 0: paper_storage_server.Paper
	(*AddPaperArgs)(nil),              // 1: paper_storage_server.AddPaperArgs
	(*AddPaperResponse)(nil),          // 2: paper_storage_server.AddPaperResponse
	(*ListPapersArgs)(nil),            // 3: paper_storage_server.ListPapersArgs
	(*ListPapersResponse)(nil),        // 4: paper_storage_server.ListPapersResponse
	(*GetPaperDetailsArgs)(nil),       // 5: paper_storage_server.GetPaperDetailsArgs
	(*GetPaperDetailsResponse)(nil),   // 6: paper_storage_server.GetPaperDetailsResponse
	(*FetchPaperContentArgs)(nil),     // 7: paper_storage_server.FetchPaperContentArgs
	(*FetchPaperContentResponse)(nil), // 8: paper_storage_server.FetchPaperContentResponse
}
var file_proto_paperStorageServer_proto_depIdxs = []int32{
	0, // 0: paper_storage_server.AddPaperArgs.paper:type_name -> paper_storage_server.Paper
	0, // 1: paper_storage_server.ListPapersResponse.papers:type_name -> paper_storage_server.Paper
	0, // 2: paper_storage_server.GetPaperDetailsResponse.paper:type_name -> paper_storage_server.Paper
	1, // 3: paper_storage_server.PaperStorageService.AddPaper:input_type -> paper_storage_server.AddPaperArgs
	3, // 4: paper_storage_server.PaperStorageService.ListPapers:input_type -> paper_storage_server.ListPapersArgs
	5, // 5: paper_storage_server.PaperStorageService.GetPaperDetails:input_type -> paper_storage_server.GetPaperDetailsArgs
	7, // 6: paper_storage_server.PaperStorageService.FetchPaperContent:input_type -> paper_storage_server.FetchPaperContentArgs
	2, // 7: paper_storage_server.PaperStorageService.AddPaper:output_type -> paper_storage_server.AddPaperResponse
	4, // 8: paper_storage_server.PaperStorageService.ListPapers:output_type -> paper_storage_server.ListPapersResponse
	6, // 9: paper_storage_server.PaperStorageService.GetPaperDetails:output_type -> paper_storage_server.GetPaperDetailsResponse
	8, // 10: paper_storage_server.PaperStorageService.FetchPaperContent:output_type -> paper_storage_server.FetchPaperContentResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_paperStorageServer_proto_init() }
func file_proto_paperStorageServer_proto_init() {
	if File_proto_paperStorageServer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_paperStorageServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paperStorageServer_proto_goTypes,
		DependencyIndexes: file_proto_paperStorageServer_proto_depIdxs,
		MessageInfos:      file_proto_paperStorageServer_proto_msgTypes,
	}.Build()
	File_proto_paperStorageServer_proto = out.File
	file_proto_paperStorageServer_proto_rawDesc = nil
	file_proto_paperStorageServer_proto_goTypes = nil
	file_proto_paperStorageServer_proto_depIdxs = nil
}
